module execute_wrapper (
    input logic clk,
    input logic rst,
    input logic decode_valid,
    input logic [4:0] decode_lsu_op,
    input logic [3:0] decode_alu_op,
    input logic [2:0] decode_env_op,
    input logic [2:0] decode_pc_op,
    input logic [3:0] decode_branch_op,
    input logic [2:0] decode_op_src_b,
    input logic [31:0] decode_rs1_data,
    input logic [31:0] decode_rs2_data,
    input logic [4:0] decode_rd_addr,
    input logic [31:0] decode_imm,
    input logic decode_reg_we,
    input logic decode_mem_re,
    input logic decode_mem_we,
    input logic [31:0] decode_pc,
    input logic memory_ready,
    output logic execute_ready,
    output logic memory_valid,
    output logic [4:0] memory_lsu_op,
    output logic [31:0] memory_result,
    output logic [31:0] memory_store_data,
    output logic [4:0] memory_rd_addr,
    output logic memory_reg_we,
    output logic update_pc,
    output logic [31:0] update_pc_target,
    output logic [3:0] alu_op,
    output logic [31:0] alu_op_a,
    output logic [31:0] alu_op_b,
    input logic [31:0] alu_result,
    input logic branch_update_pc,
    input logic [31:0] branch_update_pc_target,
    output logic [3:0] branch_op,
    output logic [31:0] branch_rs1_data,
    output logic [31:0] branch_rs2_data,
    output logic [31:0] branch_pc,
    output logic [31:0] branch_imm
);

  execute u_execute (
      .clk,
      .rst,
      .decode_execute({
        decode_valid,
        decode_lsu_op,
        decode_alu_op,
        decode_env_op,
        decode_pc_op,
        decode_branch_op,
        decode_op_src_b,
        decode_rs1_data,
        decode_rs2_data,
        decode_rd_addr,
        decode_imm,
        decode_reg_we,
        decode_mem_re,
        decode_mem_we,
        decode_pc
      }),
      .memory_ready,
      .execute_ready,
      .execute_memory({
        memory_valid, memory_lsu_op, memory_result, memory_store_data, memory_rd_addr, memory_reg_we
      }),
      .update_pc,
      .update_pc_target,
      .alu_op,
      .alu_op_a,
      .alu_op_b,
      .alu_result,
      .branch_update_pc,
      .branch_update_pc_target,
      .branch_op,
      .branch_rs1_data,
      .branch_rs2_data,
      .branch_pc,
      .branch_imm
  );

endmodule
